CREATE TABLE
IF NOT EXISTS users
(
  id INTEGER PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  age INTEGER NOT NULL,
  gender INTEGER NOT NULL,
  role INTEGER,
  created_at INTEGER NOT NULL
);