CREATE TABLE
IF NOT EXISTS sessions
(
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    value TEXT UNIQUE NOT NULL,
    expires_at INTEGER NOT NULL,

FOREIGN KEY
(user_id) REFERENCES users
(id) ON
DELETE CASCADE
);