CREATE TABLE IF NOT EXISTS comments (
	id INTEGER PRIMARY KEY,
	author_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	content TEXT NOT NULL,
	created_at INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES users (id) ON
DELETE CASCADE,
	FOREIGN KEY (post_id) REFERENCES posts (id) ON
DELETE CASCADE
);